CREATE TABLE IF NOT EXISTS users
(
	uid INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    email VARCHAR(40) NOT NULL,
    password VARCHAR(40) NOT NULL    
);

INSERT INTO USERS VALUES (1, 'admin@admin.com', 'admin');

CREATE TABLE IF NOT EXISTS posts
(
	pid INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    title VARCHAR(100),
    brief VARCHAR(300),
    body VARCHAR(1000),
    image VARCHAR(1000),
    uid INT,
    FOREIGN KEY (uid) REFERENCES users(uid)
);

INSERT INTO posts VALUES(
1, 'TITLE1', 'BRIEF1', 'BODY1', NULL, 1
);

CREATE TABLE IF NOT EXISTS comments
(
	cid INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    pid INT,
    uid INT,
    body VARCHAR(1000),
    FOREIGN KEY (pid) REFERENCES posts(pid),
    FOREIGN KEY (uid) REFERENCES users(uid)
);

INSERT INTO COMMENTS VALUES(1, 1, 1, 'COMMENT1');
INSERT INTO COMMENTS VALUES(2, 1, 1, 'COMMENT2');